version: '3.8'

services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  nestjs-app:
    image: node:16
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm run start:dev
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
